# Generated by Django 6.0 on 2026-01-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tablero'},
        ),
    ]
